### ISSUE TITLE
int[] > char[]

### ISSUE THREAD

**Issue by Pixailz** [TheEmperorPenguin/GTypes#1]
https://github.com/TheEmperorPenguin/GTypes/blob/5e5efc6c17b828fc8053cf7ee9068a57f770da68/bigInt/includes/bigInt.h#L12

Hey, i have implemented this concept in lua, for cryptography purpose, because int are float in lua, big calculation are not précise at all. unfortunately for me lua sucks a lot and calculation with an array of char is pretty heavy and as i search for solution , some one came to me and suggest to use and array of int instead of char.

In fact, using int allow for direct calculation with big number, as UINT_MAX * UINT_MAX fit in the long range, without conversion.

I could help you with this, i want something like this in my lift so np helping :)

**Comment by TheEmperorPenguin** [comment]
I haven't had the chance to work on this again, but I realized that using integers and treating the number as being in base MAX_INT (or unsigned, which is essentially the same) would be much easier and faster. Now I just need to find the time to code it.
